name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Test & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          make install
          uv add --dev coverage

      - name: Run tests and generate coverage report
        run: |
          uv run coverage run -m pytest -v
          uv run coverage xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sonarcloud=true
            -Dsonar.organization=ВАШ_КЛЮЧ_ОРГАНИЗАЦИИ
            -Dsonar.projectKey=hexlet-code
            -Dsonar.sources=gendiff,main.py
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
